[package]
name = "elemental_unrusting"
version = "0.1.0"
authors = ["Bertrand Bonnefoy-Claudet <bertrand@bertrandbc.com>"]

[dependencies]
im = "^15.1.0"
rand = "^0.8.5"
serde = "^1.0.198"
serde_derive = "^1.0.198"
serde_json = "^1.0.116"
