[package]
name = "elemental_unrusting"
version = "0.1.0"
authors = ["Bertrand Bonnefoy-Claudet <bertrandbc@gmail.com>"]

[dependencies]
im = "*"
rand = "*"
serde = "*"
serde_derive = "*"
serde_json = "*"
